project:
  type: website
  output-dir: docs
  render:
    - "*.md"

website:
  title: "R-multiverse"
  description: "A community-curated dual R package repository, powered by R-universe"
  site-url: "https://r-multiverse.org"
  favicon: "https://r-multiverse.org/logo/logo-hexbin.png"
  image: "https://r-multiverse.org/logo/logo-hexbin.png"
  open-graph: true
  navbar:
    logo: "https://r-multiverse.org/logo/logo-hexbin.png"
    logo-alt: "R-multiverse"
    left:
    - text: R-multiverse
      url: https://r-multiverse.org
    - text: Status
      url: index.md
    - text: Community
      url: community.md
    - text: Staging
      url: staging.md
    - text: Production
      url: production.md
    tools:
      - icon: github
        aria-label: "GitHub"
        menu:
          - text: Contribute
            url: https://github.com/r-multiverse/status
          - text: Report Issue
            url: https://github.com/r-multiverse/help
  page-footer:
    left: "&copy; 2025 the R-multiverse project."
    right: "<a href='https://r-consortium.org' style='text-decoration:none'>Supported by the R Consortium</a>."

format:
  html:
    theme: cosmo
    toc: true
