name: update
permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libglpk-dev

      - uses: r-lib/actions/setup-pandoc@v2
      - uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R.
        uses: r-lib/actions/setup-r@v2
        with:
          extra-repositories: https://community.r-multiverse.org
          use-public-rspm: true

      - name: Install helper R package.
        shell: Rscript {0}
        run: |
          install.packages("pak")
          pak::pkg_install("r-multiverse/multiverse.internals@*release")

      - name: Check out the status repository.
        uses: actions/checkout@v4

      - name: Check out the staging universe.
        uses: actions/checkout@v4
        with:
          repository: '${{ github.repository_owner }}/staging'
          path: 'source_staging'

      - name: Check out the community universe.
        uses: actions/checkout@v4
        with:
          repository: '${{ github.repository_owner }}/community'
          path: 'source_community'

      - name: Update package status.
        shell: Rscript {0}
        run: |
          multiverse.internals::update_status(
            path_status = getwd(),
            path_staging = "source_staging",
            path_community = "source_community"
          )

      - name: Remove staging and community universe clones.
        run: rm -rf source_staging source_community

      - name: Render site.
        run: quarto render
        
      - name: Copy package html files
        run: |
          cp -r community docs
          cp -r staging docs

      - name: Deploy to GitHub pages
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          clean: false
          branch: gh-pages
          folder: docs
